# Site settings
title: Why I Have to Be the Best Computer Programmer
header-img: img/home-bg.png
email: lorenzocovarrubiasjr@gmail.com
copyright_name: lorenzocovarrubiasjr
description: > # this means to ignore newlines until "baseurl:"
  The Reasons & Events that Made it All Make Sense
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  lorenzocovarrubiasjr
learn_profile: lorenzocovarrubiasjr
email_username: lorenzocovarrubiasjr@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
